/**
 * Admin-only tenant management — system_admin access only
 *
 * GET  /api/admin/tenants  → list all tenants (cross-tenant, superadmin only)
 * POST /api/admin/tenants  → create tenant + owner user
 *
 * Security:
 * - requireSuperAdmin() enforced before any data access
 * - tenant_id is NEVER accepted from request body
 * - All queries are intentionally cross-tenant (superadmin privilege)
 */
import type { NextApiResponse } from 'next';
import bcrypt from 'bcryptjs';
import { secureRoute, SecureRequest, getAdminDb, requireSuperAdmin } from '../../../lib/secure-route';

export default secureRoute(async (req: SecureRequest, res: NextApiResponse) => {
  // ── Authorization: superadmin only — checked BEFORE any business logic ─────
  if (!requireSuperAdmin(req, res)) return;

  const db = getAdminDb();

  // ── GET: list all tenants (cross-tenant — superadmin privilege) ────────────
  if (req.method === 'GET') {
    const { data: tenants, error } = await db
      .from('tenants')
      .select('id, business_name, slug, business_email, business_phone, is_active, theme_color, created_at')
      .order('created_at', { ascending: false });

    if (error) return res.status(500).json({ error: error.message });

    // Aggregate user counts — superadmin cross-tenant query
    const { data: userCounts } = await db.from('users').select('tenant_id');
    const countMap: Record<string, number> = {};
    userCounts?.forEach(u => {
      countMap[u.tenant_id] = (countMap[u.tenant_id] || 0) + 1;
    });

    return res.status(200).json({
      tenants: tenants?.map(t => ({ ...t, user_count: countMap[t.id] || 0 })) ?? [],
    });
  }

  // ── POST: create tenant + owner ────────────────────────────────────────────
  if (req.method === 'POST') {
    const {
      business_name,
      slug,
      business_email,
      business_phone,
      business_type = 'Retail Store',
      currency = 'KES',
      currency_symbol = 'KSh',
      theme_color = '#10b981',
      owner_name,
      owner_email,
      owner_password,
    } = req.body;

    // Input validation
    if (!business_name || !slug || !owner_email || !owner_password) {
      return res.status(400).json({ error: 'business_name, slug, owner_email, and owner_password are required' });
    }
    if (!/^[a-z0-9-]+$/.test(slug)) {
      return res.status(400).json({ error: 'Slug must be lowercase letters, numbers, and hyphens only' });
    }
    if (owner_password.length < 8) {
      return res.status(400).json({ error: 'Password must be at least 8 characters' });
    }

    // Slug uniqueness check
    const { data: existing } = await db.from('tenants').select('id').eq('slug', slug).single();
    if (existing) return res.status(409).json({ error: `Slug "${slug}" is already taken` });

    try {
      // 1. Create tenant — tenant_id is generated by DB, never from client
      const { data: tenant, error: tenantError } = await db
        .from('tenants')
        .insert({
          business_name,
          slug,
          subdomain: slug,
          business_email: business_email?.toLowerCase().trim() || null,
          business_phone: business_phone || null,
          business_type,
          currency,
          currency_symbol,
          theme_color,
          sms_sender_name: slug.toUpperCase().replace(/-/g, '_'),
          is_active: true,
        })
        .select()
        .single();

      if (tenantError) throw tenantError;

      // 2. Create Supabase auth user
      const { data: authData, error: authError } = await db.auth.admin.createUser({
        email: owner_email.toLowerCase().trim(),
        password: owner_password,
        email_confirm: true,
        user_metadata: { full_name: owner_name },
      });

      if (authError) {
        // Rollback tenant creation
        await db.from('tenants').delete().eq('id', tenant.id);
        throw authError;
      }

      // 3. Create users record — tenant_id comes from the tenant we just created, NOT from client
      const passwordHash = await bcrypt.hash(owner_password, 12);
      const { error: userError } = await db.from('users').insert({
        id: authData.user.id,
        tenant_id: tenant.id,          // ← server-assigned, never from request body
        full_name: owner_name || owner_email,
        email: owner_email.toLowerCase().trim(),
        password_hash: passwordHash,
        role: 'Admin',
        system_role: 'user',
        is_active: true,
        is_first_login: true,
      });

      if (userError) {
        // Rollback both
        await db.auth.admin.deleteUser(authData.user.id);
        await db.from('tenants').delete().eq('id', tenant.id);
        throw userError;
      }

      // 4. Create shop_settings with tenant's business info
      await db.from('shop_settings').insert({
        tenant_id: tenant.id,
        user_id: authData.user.id,
        business_name,
        business_type,
        business_email: business_email || '',
        business_phone: business_phone || '',
        business_address: '',
        business_tagline: '',
        logo_url: '',
        primary_color: theme_color,
        currency,
        currency_symbol,
        tiktok_url: '',
        instagram_url: '',
        facebook_url: '',
      });

      // 5. Seed default SMS templates for this tenant
      await db.from('message_templates').insert([
        {
          tenant_id: tenant.id,
          name: 'Thank You',
          message_text: 'Hi {customer_name}! Thank you for shopping at {shop_name}. We appreciate your business! 🙏',
          message_type: 'thank_you',
          is_active: true,
        },
      ]);

      return res.status(201).json({
        success: true,
        tenant: { id: tenant.id, business_name: tenant.business_name, slug: tenant.slug },
        owner: { id: authData.user.id, email: owner_email },
        message: `Tenant "${business_name}" created. Owner can login with ${owner_email}.`,
      });
    } catch (err: any) {
      console.error('[admin/tenants POST] error:', err);
      return res.status(500).json({ error: err.message });
    }
  }

  return res.status(405).json({ error: 'Method not allowed' });
});
